//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Logger.Targets.ObjectHistoryLogger.Data.DBScripts.OHSqlClient.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlClientQueriesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlClientQueriesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Logger.Targets.ObjectHistoryLogger.Data.DBScripts.OHSqlClient.Queries.SqlClie" +
                            "ntQueriesResource", typeof(SqlClientQueriesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	ld.&quot;ObjectLogDetailID&quot;,
        ///	ld.&quot;ObjectLogID&quot;,
        ///	ld.&quot;OperationID&quot;,
        ///	ld.&quot;LevelID&quot;,
        ///	ld.&quot;PropertyName&quot;,
        ///	ld.&quot;PropertyType&quot;,
        ///	ld.&quot;PropertyValue&quot;,
        ///	l.&quot;Name&quot; AS &quot;ObjectName&quot;,
        ///	l.&quot;ObjectType&quot; AS &quot;ObjectType&quot;, 
        ///	op.&quot;User&quot;,
        ///	op.&quot;TimeStamp&quot; AS &quot;LastModified&quot;,
        ///	op.&quot;KeyValue&quot;,
        ///	lev.&quot;Description&quot; AS &quot;Level&quot;
        ///FROM &quot;ObjectLogDetails&quot; ld
        ///LEFT JOIN &quot;ObjectLogs&quot; l ON l.&quot;ObjectLogID&quot; = ld.&quot;ObjectLogID&quot;
        ///LEFT JOIN &quot;Operations&quot; op ON op.&quot;OperaionID&quot; = ld.&quot;OperationID&quot;
        ///LEFT JOIN &quot;Levels&quot; lev ON lev.&quot;LevelID&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllObjectsHistory {
            get {
                return ResourceManager.GetString("GetAllObjectsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///				   ld.&quot;ObjectLogDetailID&quot;,
        ///				   ld.&quot;ObjectLogID&quot;,
        ///				   ld.&quot;OperationID&quot;,
        ///				   ld.&quot;LevelID&quot;,
        ///				   ld.&quot;PropertyName&quot;,
        ///				   ld.&quot;PropertyType&quot;,
        ///				   ld.&quot;PropertyValue&quot;,
        ///				   l.&quot;Name&quot; AS &quot;ObjectName&quot;,
        ///				   l.&quot;ObjectType&quot; AS &quot;ObjectType&quot;, 
        ///				   op.&quot;User&quot;,
        ///				   op.&quot;TimeStamp&quot; AS &quot;LastModified&quot;,
        ///				   op.&quot;KeyValue&quot;,
        ///				   lev.&quot;Description&quot; AS &quot;Level&quot;
        ///				   FROM &quot;ObjectLogDetails&quot; ld
        ///				
        ///				   LEFT JOIN &quot;ObjectLogs&quot; l ON l.&quot;ObjectLogID&quot; = ld.&quot;ObjectLogID&quot;
        ///				    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetObjectsLastVersion {
            get {
                return ResourceManager.GetString("GetObjectsLastVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT tbl.* FROM (SELECT 
        ///				   ld.&quot;ObjectLogDetailID&quot;,
        ///				   ld.&quot;ObjectLogID&quot;,
        ///				   ld.&quot;OperationID&quot;,
        ///				   ld.&quot;LevelID&quot;,
        ///				   ld.&quot;PropertyName&quot;,
        ///				   ld.&quot;PropertyType&quot;,
        ///				   ld.&quot;PropertyValue&quot;,
        ///				   l.&quot;Name&quot; AS &quot;ObjectName&quot;,
        ///				   l.&quot;ObjectType&quot; AS &quot;ObjectType&quot;, 
        ///				   op.&quot;User&quot;,
        ///				   op.&quot;TimeStamp&quot; AS &quot;LastModified&quot;,
        ///				   op.&quot;KeyValue&quot;,
        ///				   lev.&quot;Description&quot; AS &quot;Level&quot;
        ///				   FROM &quot;ObjectLogDetails&quot; ld
        ///				
        ///				   LEFT JOIN &quot;ObjectLogs&quot; l ON l.&quot;ObjectLogID&quot; = ld.&quot;Ob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetObjectsVersion {
            get {
                return ResourceManager.GetString("GetObjectsVersion", resourceCulture);
            }
        }
    }
}
